<a href="https://colab.research.google.com/github/EastShineK/Machine_Learning/blob/master/Life%20Coding%20Tensorflow/Classification_of_Iris_varieties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [4]:
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [7]:
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [9]:
# 3.데이터로 모델을 학습(FIT)
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1716 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1715 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1713 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1714 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1709 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1716 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1704 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1713 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1703 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1705 - accuracy: 0.9667


In [10]:
# 4. 모델을 이용
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9863786e-01 1.3619534e-03 2.2408584e-07]
 [9.9524385e-01 4.7542383e-03 1.8513568e-06]
 [9.9757701e-01 2.4223395e-03 6.7094646e-07]
 [9.9413139e-01 5.8662868e-03 2.3970160e-06]
 [9.9886876e-01 1.1311127e-03 1.6478903e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [11]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.1526503e-06 1.0979798e-01 8.9020079e-01]
 [2.8640795e-06 1.7964427e-01 8.2035279e-01]
 [5.3455901e-06 2.3499636e-01 7.6499832e-01]
 [1.5749787e-06 1.3738266e-01 8.6261576e-01]
 [1.4340725e-05 3.4446263e-01 6.5552306e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [12]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.520068  ,  0.05753264, -0.30433252],
       [ 3.1369307 ,  0.8149042 , -0.76340556],
       [-2.706543  ,  0.340914  ,  1.3148396 ],
       [-4.2679563 , -1.3819978 ,  1.900916  ]], dtype=float32), array([ 2.3351533,  1.3800737, -1.9828099], dtype=float32)]
